// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "./BatchToken.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

contract AggregationManager is ReentrancyGuard, AccessControl {
    bytes32 public constant ADMIN_ROLE = DEFAULT_ADMIN_ROLE;
    bytes32 public constant AGGREGATOR_ROLE = keccak256("AGGREGATOR_ROLE");

    BatchToken public batchToken;

    event Aggregated(uint256 indexed parentId, uint256[] children, address indexed aggregator, uint256 timestamp);

    constructor(address admin, address batchTokenAddress) {
        require(admin != address(0), "admin zero");
        _setupRole(ADMIN_ROLE, admin);
        batchToken = BatchToken(batchTokenAddress);
    }

    /// @notice Aggregate children into a parent. Caller must have AGGREGATOR_ROLE on this contract.
    function aggregate(
        address to,
        string calldata parentCid,
        bytes32 parentLocationHash,
        uint256[] calldata children
    ) external nonReentrant returns (uint256) {
        require(hasRole(AGGREGATOR_ROLE, msg.sender), "not aggregator here");

        // validate children are present and currently unaggregated
        for (uint i = 0; i < children.length; ++i) {
            require(batchToken.ownerOf(children[i]) != address(0), "child missing");

            // unpack child batch tuple returned by the public getter
            (uint256 childId, string memory cid, bytes32 locHash, uint256 ts, uint256 childParentId, uint8 state) = _readBatch(children[i]);
            require(childParentId == 0, "child already aggregated");
        }

        // mint parent (this contract must have ADMIN_ROLE on BatchToken)
        uint256 parentTokenId = batchToken.adminMintParent(to, parentCid, parentLocationHash);

        // set parent for each child
        for (uint i = 0; i < children.length; ++i) {
            batchToken.setParent(children[i], parentTokenId);
        }

        emit Aggregated(parentTokenId, children, msg.sender, block.timestamp);
        return parentTokenId;
    }

    /// @notice Read a batch tuple from BatchToken via its autogenerated public getter.
    /// Returns (id, metadataCID, locationHash, timestamp, parentId, state)
    function _readBatch(uint256 tokenId) internal view returns (uint256, string memory, bytes32, uint256, uint256, uint8) {
        // The public mapping accessor in BatchToken returns a tuple, so we can directly return it.
        return batchToken.batches(tokenId);
    }
}
